{% set name = "harfbuzz" %}
{% set version = "10.2.0" %}
{% set sha256 = "11749926914fd488e08e744538f19329332487a6243eec39ef3c63efa154a578" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/harfbuzz/harfbuzz/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:                          # [win or linux]
    - fix-win-gir.patch             # [win]
    # check-libstdc++.py fails on linux with a message
    # 'Ouch, $SRC_DIR/builddir/src/libharfbuzz-cairo.so is linked to libstdc++ or libc++',
    # but checking by 'readelf -a $SRC_DIR/builddir/src/libharfbuzz-cairo.so' it was verified
    # that there are no linking to ibstdc++ or libc++. So skipping the test.
    - disable-check-libstdxx.patch  # [linux]
build:
  number: 1
  run_exports:
    # pretty excellent forward compatibility
    # https://abi-laboratory.pro/index.php?view=timeline&l=harfbuzz
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - gobject-introspection
    - meson
    - ninja-base
    - pthread-stubs
    - m2-patch  # [win]
    - patch     # [linux]
  host:
    - gobject-introspection 1.78.1
    - cairo {{ cairo }}
    - freetype {{ freetype }}
    - glib {{ glib }}
    - icu {{ icu }}
    - graphite2 1.3.14
    # # xorg/xcb packages are needed for cairo support.
    # - xorg-libxau  # [linux]
    # - xorg-libxext  # [linux]
    # - xorg-libx11  # [linux]
    # - xorg-libxrender  # [linux]
    # - xorg-xorgproto  # [linux]
  run:
    - cairo                              # [not win]
    - freetype
    - icu
    - graphite2

test:
  commands:
    # Libraries/headers.
    {% set libs = ["harfbuzz-cairo", "harfbuzz-gobject", "harfbuzz-icu", "harfbuzz-subset", "harfbuzz"] %}
    {% for lib in libs %}
    - test -f $PREFIX/lib/lib{{ lib }}${SHLIB_EXT}                   # [unix]
    - test -f $PREFIX/lib/pkgconfig/{{ lib }}.pc                     # [unix]
    - if not exist %PREFIX%\Library\bin\{{ lib }}.dll exit 1         # [win]
    {% endfor %}
    - test -f $PREFIX/include/harfbuzz/hb-ft.h                       # [not win]
    - if not exist %PREFIX%\Library\include\harfbuzz\hb-ft.h exit 1  # [win]
    - test -f $PREFIX/lib/girepository-1.0/HarfBuzz-0.0.typelib      # [unix]
    - if not exist %PREFIX%\Library\lib\girepository-1.0\HarfBuzz-0.0.typelib exit 1  # [win]
    - test -f $PREFIX/share/gir-1.0/HarfBuzz-0.0.gir                 # [not win]
    # CLI tests.
    - hb-view --version  # [linux]

about:
  home: https://harfbuzz.github.io/
  license: MIT
  license_file: COPYING
  license_family: MIT
  summary: A text shaping library.
  description: |
    HarfBuzz is a text shaping library. Using the HarfBuzz library allows
    programs to convert a sequence of Unicode input into properly formatted
    and positioned glyph output—for any writing system and language.
  doc_url: https://harfbuzz.github.io/
  dev_url: https://github.com/harfbuzz/harfbuzz

extra:
  recipe-maintainers:
    - ocefpaf
    - pkgw
