{% set name = "harfbuzz" %}
{% set version = "12.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/harfbuzz/harfbuzz/archive/{{ version }}.tar.gz
  sha256: e93af4816128fc0a02d2e84106fdfe36a3fde01086b723be8f0656a65562ca9e
  patches:
    - gir-windows.patch  # [win]
    - createfontdescriptors.patch  # [osx]

build:
  number: 1
  run_exports:
    # pretty excellent forward compatibility
    # https://abi-laboratory.pro/index.php?view=timeline&l=harfbuzz
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - gobject-introspection
    # Newer version glib have no GObject-2.0.gir, so that we link to older one
    - glib
    - meson
    - ninja-base
    - pkg-config
    - pthread-stubs
  host:
    - cairo {{ cairo }}
    # Newer version glib have no GObject-2.0.gir, so that we link to older one
    - glib
    - freetype {{ freetype }}
    - icu {{ icu }}
    - graphite2 {{ graphite2 }}
  run:
    # Still doesn't have run export as of 2025/07/26
    # https://github.com/conda-forge/graphite2-feedstock/pull/19
    - graphite2

test:
  commands:
    # Libraries/headers.
    {% set libs = ["harfbuzz-cairo", "harfbuzz-gobject", "harfbuzz-icu", "harfbuzz-subset", "harfbuzz"] %}
    {% for lib in libs %}
    - test -f $PREFIX/lib/lib{{ lib }}${SHLIB_EXT}    # [unix]
    - if not exist %PREFIX%\Library\bin\{{ lib }}.dll exit 1       # [win]
    {% endfor %}
    - test -f $PREFIX/include/harfbuzz/hb-ft.h    # [not win]
    - if not exist %PREFIX%\Library\include\harfbuzz\hb-ft.h exit 1         # [win]
    - test -f $PREFIX/lib/girepository-1.0/HarfBuzz-0.0.typelib    # [unix]
    - if not exist %PREFIX%\Library\lib\girepository-1.0\HarfBuzz-0.0.typelib exit 1         # [win]
    - test -f $PREFIX/share/gir-1.0/HarfBuzz-0.0.gir                 # [not win]
    # CLI tests.
    - hb-view --version  # [linux]

about:
  home: https://harfbuzz.github.io
  license: MIT
  license_file: COPYING
  license_family: MIT
  summary: An OpenType text shaping engine.
  description: |
    HarfBuzz is a text shaping library. Using the HarfBuzz library allows
    programs to convert a sequence of Unicode input into properly formatted
    and positioned glyph output—for any writing system and language.
  doc_url: https://harfbuzz.github.io
  dev_url: https://github.com/harfbuzz/harfbuzz

extra:
  recipe-maintainers:
    - ocefpaf
    - pkgw
    - tschoonj
