{% set version = "1.3.4" %}

package:
  name: harfbuzz
  version: {{ version }}

source:
  fn: harfbuzz-{{ version }}.tar.bz2
  url: http://www.freedesktop.org/software/harfbuzz/release/harfbuzz-{{ version }}.tar.bz2
  sha256: 718aa6fcadef1a6548315b8cfe42cc27e926256302c337f42df3a443843f6a2b

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - automake
    - libtool
    - pkg-config
    - cairo 1.14.*
    - glib 2.51.*
    - freetype 2.6.*
    - icu 56.*
  run:
    - cairo 1.14.*
    - glib 2.51.*
    - freetype 2.6.*
    - icu 56.*

test:
  commands:
    # Libraries/headers.
    {% set libs = [
        "libharfbuzz-icu",
        "libharfbuzz"
        ] %}
    {% for lib in libs %}
    - test -f $PREFIX/lib/{{ lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/{{ lib }}.so  # [linux]
    - test -f $PREFIX/include/harfbuzz/hb-ft.h  # [not win]
    {% endfor %}
    # CLI tests.
    - hb-view --version  # [linux]
    - conda inspect linkages -p $PREFIX harfbuzz  # [not win]
    - conda inspect objects -p $PREFIX harfbuzz  # [osx]

about:
  home: http://www.freedesktop.org/wiki/Software/HarfBuzz/
  license: MIT
  license_file: COPYING
  summary: 'An OpenType text shaping engine.'
  description: |
    HarfBuzz is a text shaping library. New Harbuzz targets various font
    technologies while Old HarfBuzz targets only OpenType fonts.
  doc_url: https://www.freedesktop.org/wiki/Software/HarfBuzz/
  dev_url: https://github.com/behdad/harfbuzz

extra:
  recipe-maintainers:
    - ocefpaf
