{% set name = "harfbuzz" %}
{% set version = "3.3.1" %}
{% set sha256 = "45aca6428d718e08872ad37647081c1b85c5b349c8419af84c04da17cf14b570" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/harfbuzz/harfbuzz/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  run_exports:
    # removes symbols rarely (last time in 2014).
    #    https://abi-laboratory.pro/tracker/timeline/harfbuzz/
    - {{ pin_subpackage('harfbuzz') }}
  missing_dso_whitelist:
    - $RPATH/libm.so.6
    - $RPATH/libc.so.6

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux and s390x]; needed for cairo support
    - gobject-introspection              # [not win]
    - meson
    - ninja
    - pkg-config
    - pthread-stubs
  host:
    - cairo
    - freetype
    - glib
    - icu
    - graphite2
  run:
    - cairo
    - freetype
    - icu
    - graphite2

test:
  commands:
    # Libraries/headers.
    {% set libs = [
        "libharfbuzz-icu",
        "libharfbuzz"
        ] %}
    {% for lib in libs %}
    - test -f $PREFIX/lib/{{ lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/{{ lib }}.so  # [linux]
    {% endfor %}
    - test -f $PREFIX/include/harfbuzz/hb-ft.h  # [not win]
    - test -f $PREFIX/share/gir-1.0/HarfBuzz-0.0.gir  # [not win]
    # CLI tests.
    - hb-view --version  # [linux]

about:
  home: http://www.freedesktop.org/wiki/Software/HarfBuzz/
  license: MIT
  license_file: COPYING
  license_family: MIT
  summary: An OpenType text shaping engine.
  description: |
    HarfBuzz is a text shaping library. New Harbuzz targets various font
    technologies while Old HarfBuzz targets only OpenType fonts.
  doc_url: https://www.freedesktop.org/wiki/Software/HarfBuzz/
  dev_url: https://github.com/behdad/harfbuzz

extra:
  recipe-maintainers:
    - ocefpaf
    - pkgw
