travis:
  secure:
    BINSTAR_TOKEN: UUMP7fCMm8VoSup4tIGfDCP7oypfN6ZFT+PzRNt4eShHfyYKWJMfCPBIC/Sv7pTf13lsRJQrQrF74CBu8lRy4ZuvV5plp0DEVJErMnUzSL/Qca5tcmxkXLXEINtByIuQfhwdPtSIe0zVWTDlX7ioZ0C/4tjukrviF0vq5lFTGundZzal8xl8rzlKUOPoTn/kFcoODzfN7YedySk+SxuqgpakKg7OowbWwWTxsNieh23oHl/EWoUgBGYAS0WA78nRoSyMlKUGsIvHQI9BNXOPtx4uH9IWD6dR9DxeyXgyUBMBpthQoIBW0H5D9fR+awLHW7eaZg2HfKT7zVidz8gjLvAvi50xpOlti4l1nk3mtenC9FCTGnR5k83Y/sQBW+bcUKbx+yH7PvIfuTY6UldkaYUC0odXR6cursmmW9X1v0VRcJPXZ7yPPMmlm34ZLKSto5x+4DwNounOLXnKzjoSNPJiwTXDat53J6rm8aCl5376DXW4X5kLqu1U+JM5yJK0Xb+Lm5AU3l6ogY47hkICqJRxl08t/xkPfT6i3HrPQYb34gOozi0rFAS2lerIisGRBVLoGci+OtLYwhA0txl2jNKRRmAOGvGuslBACkyiYJN3UyPih+2mw32pf45de5KDeaFHZKhT0znIAjr1x8KR+mhEaDIFg6z7BD+jXiWMIxw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
